//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResponseStates.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ResponseStates.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APIMobileUnexpectedError.
        /// </summary>
        internal static string APIMobileUnexpectedError {
            get {
                return ResourceManager.GetString("APIMobileUnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APIPosUnexpectedError.
        /// </summary>
        internal static string APIPosUnexpectedError {
            get {
                return ResourceManager.GetString("APIPosUnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppealCreditSuccess.
        /// </summary>
        internal static string AppealCreditSuccess {
            get {
                return ResourceManager.GetString("AppealCreditSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppealError.
        /// </summary>
        internal static string AppealError {
            get {
                return ResourceManager.GetString("AppealError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppealLoadCreditSuccess.
        /// </summary>
        internal static string AppealLoadCreditSuccess {
            get {
                return ResourceManager.GetString("AppealLoadCreditSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppealSuccess.
        /// </summary>
        internal static string AppealSuccess {
            get {
                return ResourceManager.GetString("AppealSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppKeyDeleted.
        /// </summary>
        internal static string AppKeyDeleted {
            get {
                return ResourceManager.GetString("AppKeyDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppKeyExpiry.
        /// </summary>
        internal static string AppKeyExpiry {
            get {
                return ResourceManager.GetString("AppKeyExpiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppKeyPassive.
        /// </summary>
        internal static string AppKeyPassive {
            get {
                return ResourceManager.GetString("AppKeyPassive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppKeyWrong.
        /// </summary>
        internal static string AppKeyWrong {
            get {
                return ResourceManager.GetString("AppKeyWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BlockedUser.
        /// </summary>
        internal static string BlockedUser {
            get {
                return ResourceManager.GetString("BlockedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CardAdd.
        /// </summary>
        internal static string CardAdd {
            get {
                return ResourceManager.GetString("CardAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CardBlocked.
        /// </summary>
        internal static string CardBlocked {
            get {
                return ResourceManager.GetString("CardBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CardDeleted.
        /// </summary>
        internal static string CardDeleted {
            get {
                return ResourceManager.GetString("CardDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CardDeleteSuccess.
        /// </summary>
        internal static string CardDeleteSuccess {
            get {
                return ResourceManager.GetString("CardDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CardFoundSame.
        /// </summary>
        internal static string CardFoundSame {
            get {
                return ResourceManager.GetString("CardFoundSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CardInActive.
        /// </summary>
        internal static string CardInActive {
            get {
                return ResourceManager.GetString("CardInActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CardLoadCredit.
        /// </summary>
        internal static string CardLoadCredit {
            get {
                return ResourceManager.GetString("CardLoadCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CardNotCreate.
        /// </summary>
        internal static string CardNotCreate {
            get {
                return ResourceManager.GetString("CardNotCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CardNotDelete.
        /// </summary>
        internal static string CardNotDelete {
            get {
                return ResourceManager.GetString("CardNotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CardNotFound.
        /// </summary>
        internal static string CardNotFound {
            get {
                return ResourceManager.GetString("CardNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CardNotIncludeID.
        /// </summary>
        internal static string CardNotIncludeID {
            get {
                return ResourceManager.GetString("CardNotIncludeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CardNotUpdate.
        /// </summary>
        internal static string CardNotUpdate {
            get {
                return ResourceManager.GetString("CardNotUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CardUpdateSuccess.
        /// </summary>
        internal static string CardUpdateSuccess {
            get {
                return ResourceManager.GetString("CardUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talebiniz alınmıştır..
        /// </summary>
        internal static string CardUserAdd {
            get {
                return ResourceManager.GetString("CardUserAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommissionDeleted.
        /// </summary>
        internal static string CommissionDeleted {
            get {
                return ResourceManager.GetString("CommissionDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommissionNotFound.
        /// </summary>
        internal static string CommissionNotFound {
            get {
                return ResourceManager.GetString("CommissionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompanyAppealCreated.
        /// </summary>
        internal static string CompanyAppealCreated {
            get {
                return ResourceManager.GetString("CompanyAppealCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompanyAppealNotCreated.
        /// </summary>
        internal static string CompanyAppealNotCreated {
            get {
                return ResourceManager.GetString("CompanyAppealNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotCompanyAppealSendMail.
        /// </summary>
        internal static string CompanyAppealNotSendMail {
            get {
                return ResourceManager.GetString("CompanyAppealNotSendMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompanyBlocked.
        /// </summary>
        internal static string CompanyBlocked {
            get {
                return ResourceManager.GetString("CompanyBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompanyFoundSame.
        /// </summary>
        internal static string CompanyFoundSame {
            get {
                return ResourceManager.GetString("CompanyFoundSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompanyNoContent.
        /// </summary>
        internal static string CompanyNoContent {
            get {
                return ResourceManager.GetString("CompanyNoContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompanyNotDelete.
        /// </summary>
        internal static string CompanyNotDelete {
            get {
                return ResourceManager.GetString("CompanyNotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompanyNotSameID.
        /// </summary>
        internal static string CompanyNotSameID {
            get {
                return ResourceManager.GetString("CompanyNotSameID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompanyNotUpdate.
        /// </summary>
        internal static string CompanyNotUpdate {
            get {
                return ResourceManager.GetString("CompanyNotUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeletedUser.
        /// </summary>
        internal static string DeletedUser {
            get {
                return ResourceManager.GetString("DeletedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FleetFoundSame.
        /// </summary>
        internal static string FleetFoundSame {
            get {
                return ResourceManager.GetString("FleetFoundSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GasStationBlocked.
        /// </summary>
        internal static string GasStationBlocked {
            get {
                return ResourceManager.GetString("GasStationBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GasStationDeleted.
        /// </summary>
        internal static string GasStationDeleted {
            get {
                return ResourceManager.GetString("GasStationDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GasStationInActive.
        /// </summary>
        internal static string GasStationInActive {
            get {
                return ResourceManager.GetString("GasStationInActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GasStationNotFound.
        /// </summary>
        internal static string GasStationNotFound {
            get {
                return ResourceManager.GetString("GasStationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InActiveUser.
        /// </summary>
        internal static string InActiveUser {
            get {
                return ResourceManager.GetString("InActiveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoadBalanceError.
        /// </summary>
        internal static string LoadBalanceError {
            get {
                return ResourceManager.GetString("LoadBalanceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoadBalanceSuccess.
        /// </summary>
        internal static string LoadBalanceSuccess {
            get {
                return ResourceManager.GetString("LoadBalanceSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MailForgotPasswordSendSucces.
        /// </summary>
        internal static string MailForgotPasswordSendSucces {
            get {
                return ResourceManager.GetString("MailForgotPasswordSendSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ManagementUIValidationError.
        /// </summary>
        internal static string ManagementUIValidationError {
            get {
                return ResourceManager.GetString("ManagementUIValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoContent.
        /// </summary>
        internal static string NoContent {
            get {
                return ResourceManager.GetString("NoContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotEnoughCredit.
        /// </summary>
        internal static string NotEnoughCredit {
            get {
                return ResourceManager.GetString("NotEnoughCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotFoundCode.
        /// </summary>
        internal static string NotFoundCode {
            get {
                return ResourceManager.GetString("NotFoundCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotFoundUser.
        /// </summary>
        internal static string NotFoundUser {
            get {
                return ResourceManager.GetString("NotFoundUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotPosUser.
        /// </summary>
        internal static string NotPosUser {
            get {
                return ResourceManager.GetString("NotPosUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotSendMail.
        /// </summary>
        internal static string NotSendMail {
            get {
                return ResourceManager.GetString("NotSendMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NumberPlateCountZero.
        /// </summary>
        internal static string NumberPlateCountZero {
            get {
                return ResourceManager.GetString("NumberPlateCountZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NumberPlateCreate.
        /// </summary>
        internal static string NumberPlateCreate {
            get {
                return ResourceManager.GetString("NumberPlateCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plaka ekleme işlemi sırasında bir hata oluştuğundan dolayı işleminiz tamamlanamamıştır..
        /// </summary>
        internal static string NumberPlateNotCreate {
            get {
                return ResourceManager.GetString("NumberPlateNotCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NumberPlateNotFound.
        /// </summary>
        internal static string NumberPlateNotFound {
            get {
                return ResourceManager.GetString("NumberPlateNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NumberPlateNotMatchUser.
        /// </summary>
        internal static string NumberPlateNotMatchUser {
            get {
                return ResourceManager.GetString("NumberPlateNotMatchUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NumberPlateNotRemove.
        /// </summary>
        internal static string NumberPlateNotRemove {
            get {
                return ResourceManager.GetString("NumberPlateNotRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NumberPlateRemove.
        /// </summary>
        internal static string NumberPlateRemove {
            get {
                return ResourceManager.GetString("NumberPlateRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OilStationError.
        /// </summary>
        internal static string OilStationError {
            get {
                return ResourceManager.GetString("OilStationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OilStationFoundSame.
        /// </summary>
        internal static string OilStationFoundSame {
            get {
                return ResourceManager.GetString("OilStationFoundSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OilStationSuccess.
        /// </summary>
        internal static string OilStationSuccess {
            get {
                return ResourceManager.GetString("OilStationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PosMachineAppealCreated.
        /// </summary>
        internal static string PosMachineAppealCreated {
            get {
                return ResourceManager.GetString("PosMachineAppealCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PosMachineCreated.
        /// </summary>
        internal static string PosMachineCreated {
            get {
                return ResourceManager.GetString("PosMachineCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PosMachineDeleted.
        /// </summary>
        internal static string PosMachineDeleted {
            get {
                return ResourceManager.GetString("PosMachineDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PosMachineFoundSame.
        /// </summary>
        internal static string PosMachineFoundSame {
            get {
                return ResourceManager.GetString("PosMachineFoundSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PosMachineInActive.
        /// </summary>
        internal static string PosMachineInActive {
            get {
                return ResourceManager.GetString("PosMachineInActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PosMachineNotCreated.
        /// </summary>
        internal static string PosMachineNotCreated {
            get {
                return ResourceManager.GetString("PosMachineNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PosMachineNotFound.
        /// </summary>
        internal static string PosMachineNotFound {
            get {
                return ResourceManager.GetString("PosMachineNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QRTransactionCanceled.
        /// </summary>
        internal static string QRTransactionCanceled {
            get {
                return ResourceManager.GetString("QRTransactionCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QRTransactionCantPrintReceipt.
        /// </summary>
        internal static string QRTransactionCantPrintReceipt {
            get {
                return ResourceManager.GetString("QRTransactionCantPrintReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QRTransactionConfirmed.
        /// </summary>
        internal static string QRTransactionConfirmed {
            get {
                return ResourceManager.GetString("QRTransactionConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QRTransactionNotCanceled.
        /// </summary>
        internal static string QRTransactionNotCanceled {
            get {
                return ResourceManager.GetString("QRTransactionNotCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QRTransactionNotConfirmed.
        /// </summary>
        internal static string QRTransactionNotConfirmed {
            get {
                return ResourceManager.GetString("QRTransactionNotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QRTransactionNotCreate.
        /// </summary>
        internal static string QRTransactionNotCreate {
            get {
                return ResourceManager.GetString("QRTransactionNotCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QRTransactionNotFound.
        /// </summary>
        internal static string QRTransactionNotFound {
            get {
                return ResourceManager.GetString("QRTransactionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QRTransactionNotRejeted.
        /// </summary>
        internal static string QRTransactionNotRejeted {
            get {
                return ResourceManager.GetString("QRTransactionNotRejeted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QRTransactionNotTimeOut.
        /// </summary>
        internal static string QRTransactionNotTimeOut {
            get {
                return ResourceManager.GetString("QRTransactionNotTimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QRTransactionNotWaiting.
        /// </summary>
        internal static string QRTransactionNotWaiting {
            get {
                return ResourceManager.GetString("QRTransactionNotWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QRTransactionRejeted.
        /// </summary>
        internal static string QRTransactionRejeted {
            get {
                return ResourceManager.GetString("QRTransactionRejeted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QRTransactionTimeOut.
        /// </summary>
        internal static string QRTransactionTimeOut {
            get {
                return ResourceManager.GetString("QRTransactionTimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TokenExpiry.
        /// </summary>
        internal static string TokenExpiry {
            get {
                return ResourceManager.GetString("TokenExpiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TokenInvalid.
        /// </summary>
        internal static string TokenInvalid {
            get {
                return ResourceManager.GetString("TokenInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TokenNotFound.
        /// </summary>
        internal static string TokenNotFound {
            get {
                return ResourceManager.GetString("TokenNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TransactionNoContent.
        /// </summary>
        internal static string TransactionNoContent {
            get {
                return ResourceManager.GetString("TransactionNoContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TransactionNotCreate.
        /// </summary>
        internal static string TransactionNotCreate {
            get {
                return ResourceManager.GetString("TransactionNotCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotEnoughDistance.
        /// </summary>
        internal static string TransactionNotEnoughDistance {
            get {
                return ResourceManager.GetString("TransactionNotEnoughDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TransactionTypeNotCreate.
        /// </summary>
        internal static string TransactionTypeNotCreate {
            get {
                return ResourceManager.GetString("TransactionTypeNotCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TransactionTypeNotFound.
        /// </summary>
        internal static string TransactionTypeNotFound {
            get {
                return ResourceManager.GetString("TransactionTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TransactionWrongCardType.
        /// </summary>
        internal static string TransactionWrongCardType {
            get {
                return ResourceManager.GetString("TransactionWrongCardType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized.
        /// </summary>
        internal static string Unauthorized {
            get {
                return ResourceManager.GetString("Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnexpectedError.
        /// </summary>
        internal static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserChangedPassword.
        /// </summary>
        internal static string UserChangedPassword {
            get {
                return ResourceManager.GetString("UserChangedPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserChangePassword.
        /// </summary>
        internal static string UserChangePassword {
            get {
                return ResourceManager.GetString("UserChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserCodeExpriy.
        /// </summary>
        internal static string UserCodeExpriy {
            get {
                return ResourceManager.GetString("UserCodeExpriy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserCodeNotCreated.
        /// </summary>
        internal static string UserCodeNotCreated {
            get {
                return ResourceManager.GetString("UserCodeNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserCreate.
        /// </summary>
        internal static string UserCreate {
            get {
                return ResourceManager.GetString("UserCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserForgotPasswordSendSucces.
        /// </summary>
        internal static string UserForgotPasswordSendSucces {
            get {
                return ResourceManager.GetString("UserForgotPasswordSendSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserFound.
        /// </summary>
        internal static string UserFound {
            get {
                return ResourceManager.GetString("UserFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserFoundSame.
        /// </summary>
        internal static string UserFoundSame {
            get {
                return ResourceManager.GetString("UserFoundSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserNotChangedPassword.
        /// </summary>
        internal static string UserNotChangedPassword {
            get {
                return ResourceManager.GetString("UserNotChangedPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserNotCreate.
        /// </summary>
        internal static string UserNotCreate {
            get {
                return ResourceManager.GetString("UserNotCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserNotSameID.
        /// </summary>
        internal static string UserNotSameID {
            get {
                return ResourceManager.GetString("UserNotSameID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserNotUpdate.
        /// </summary>
        internal static string UserNotUpdate {
            get {
                return ResourceManager.GetString("UserNotUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserPasswordConfirm.
        /// </summary>
        internal static string UserPasswordConfirm {
            get {
                return ResourceManager.GetString("UserPasswordConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserUpdate.
        /// </summary>
        internal static string UserUpdate {
            get {
                return ResourceManager.GetString("UserUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValidationError.
        /// </summary>
        internal static string ValidationError {
            get {
                return ResourceManager.GetString("ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebUIValidationError.
        /// </summary>
        internal static string WebUIValidationError {
            get {
                return ResourceManager.GetString("WebUIValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WrongMail.
        /// </summary>
        internal static string WrongMail {
            get {
                return ResourceManager.GetString("WrongMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WrongPassword.
        /// </summary>
        internal static string WrongPassword {
            get {
                return ResourceManager.GetString("WrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WrongUser.
        /// </summary>
        internal static string WrongUser {
            get {
                return ResourceManager.GetString("WrongUser", resourceCulture);
            }
        }
    }
}
